[package]
name = "porto/zombiemania"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rewire = "sayhisam1/rewire@0.3.0"
promise = "evaera/promise@4.0.0"
net = "vorlias/net@3.0.1"
signal = "sleitnick/signal@1.2.1"
janitor = "howmanysmall/janitor@1.14.1"
matter = "evaera/matter@0.6.2"
plasma = "evaera/plasma@0.4.2"
gameanalytics = "gameanalytics/gameanalytics-sdk@2.2.2"
cmdr = "evaera/cmdr@1.9.0"
t = "osyrisrblx/t@3.0.0"
llama = "freddylist/llama@1.1.1"
matterhooks = "lasttalon/matter-hooks@0.1.0"

[server-dependencies]
profileservice = "alreadypro/profileservice@1.0.4"
